name: build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Clean files
      run: |
        rm -R assets
        rm -R .github
        rm -R files
        mv run.sh index.html
        mkdir user
        mv run_user.sh user/index.html

    - name: Init git and commit
      env:
        DEPLOY_PRIVATE: ${{ secrets.DEPLOY_PRIVATE }}
      run: |
        mkdir -p ~/.ssh/
        echo "$DEPLOY_PRIVATE" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        git config --global user.email "smczx@hotmail.com"
        git config --global user.name "ControlNet"
        rm -rf .git
        git init
        git add -A
        git commit -m "update"
        git remote add origin-ssh git@github.com:ControlNet/my-zsh-theme-env.git

    - name: Push
      run: |
        git push origin-ssh HEAD:dist -f