name: Test

on:
  push:
    branches-ignore:
      - main
  pull_request:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: prefix-dev/setup-pixi@v0.8.3
        with:
          pixi-version: v0.47.0
          cache: true
          manifest-path: pyproject.toml

      - name: Run tests
        run: pixi run test

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: |
            test-results.xml
            coverage.xml
          retention-days: 30 