name: test
on:
  push:
    branches:
      - main
  pull_request:
        
jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, centos, fedora, manjaro, arch]
        mode: [sudo, user]
    name: ${{ matrix.os }} ${{ matrix.mode }} test
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build docker image
        run: docker build -f .github/integration-test/Dockerfile-${{ matrix.os }}-${{ matrix.mode }} -t test_os .
      
      - name: Run docker container
        run: docker run --rm --privileged=true -it test_os